# Generated by Django 4.2.7 on 2025-08-02 17:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('printer_type', models.CharField(choices=[('laser', 'Laser'), ('inkjet', 'Inkjet'), ('thermal', 'Thermal'), ('dot_matrix', 'Dot Matrix')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('network_path', models.CharField(blank=True, max_length=255)),
                ('supports_color', models.BooleanField(default=False)),
                ('supports_duplex', models.BooleanField(default=False)),
                ('max_paper_size', models.CharField(default='A4', max_length=10)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('busy', 'Busy'), ('error', 'Error'), ('maintenance', 'Maintenance')], default='offline', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('total_pages_printed', models.IntegerField(default=0)),
                ('last_maintenance', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Printer',
                'verbose_name_plural': 'Printers',
                'db_table': 'printers',
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('copies', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('pages', models.CharField(default='all', max_length=100)),
                ('color_mode', models.CharField(choices=[('color', 'Color'), ('bw', 'Black & White'), ('grayscale', 'Grayscale')], default='bw', max_length=10)),
                ('paper_size', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('Letter', 'Letter'), ('Legal', 'Legal'), ('Custom', 'Custom')], default='A4', max_length=10)),
                ('print_quality', models.CharField(choices=[('draft', 'Draft'), ('normal', 'Normal'), ('high', 'High'), ('best', 'Best')], default='normal', max_length=10)),
                ('duplex', models.BooleanField(default=False)),
                ('collate', models.BooleanField(default=True)),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('printing', 'Printing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='pending', max_length=20)),
                ('priority', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('cost_per_page', models.DecimalField(decimal_places=2, default=0.1, max_digits=6)),
                ('total_pages', models.IntegerField(default=1)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tokens_required', models.IntegerField(default=1)),
                ('tokens_deducted', models.BooleanField(default=False)),
                ('pages_printed', models.IntegerField(default=0)),
                ('progress_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_completion', models.DateTimeField(blank=True, null=True)),
                ('job_settings', models.JSONField(blank=True, default=dict)),
                ('print_metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Print Job',
                'verbose_name_plural': 'Print Jobs',
                'db_table': 'print_jobs',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintJobLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Print Job Log',
                'verbose_name_plural': 'Print Job Logs',
                'db_table': 'print_job_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PrintJobStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Print Job Status History',
                'verbose_name_plural': 'Print Job Status Histories',
                'db_table': 'print_job_status_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PrintQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('estimated_start_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_duration', models.DurationField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('print_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='print_jobs.printjob')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='print_jobs.printer')),
            ],
            options={
                'verbose_name': 'Print Queue Entry',
                'verbose_name_plural': 'Print Queue Entries',
                'db_table': 'print_queue',
                'ordering': ['position'],
            },
        ),
    ]
