# Generated by Django 4.2.7 on 2025-08-02 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('print_jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjobstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='printjobstatushistory',
            name='print_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='print_jobs.printjob'),
        ),
        migrations.AddField(
            model_name='printjoblog',
            name='print_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='print_jobs.printjob'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='files.file'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='printer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='print_jobs.printer'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='printqueue',
            unique_together={('printer', 'position')},
        ),
    ]
